version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.1
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
      - run:
          name: Run Django tests
          command: pipenv run python manage.py test

workflows:
  on_commit:
    jobs:
      - build_and_test
